version : '3'

tasks:

  # Build packages
  build: 
    desc: Build the current package against the unstable repo
    dir: '{{ .USER_WORKING_DIR }}'
    vars:
      PROFILE: '{{ default "unstable-x86_64" .PROFILE }}'
      SPECFILE:
        sh: if [ -f package.yml ]; then echo "package.yml"; else echo "pspec.xml"; fi;
    preconditions:
      - test -f package.yml || test -f pspec.xml
    cmds:
      - sudo solbuild build {{ .SPECFILE }} -p {{ .PROFILE }} {{ .CLI_ARGS }}

  build-stable:
    desc: Build the current package against the stable repo (do NOT use for official submissions!)
    cmds:
      - task: build
        vars: 
          PROFILE: 'main-x86_64'
      - |
        echo "=========================================================================="
        echo "WARNING: This package was built against -stable and is for local use only."
        echo "                                                                          "
        echo "         Do NOT publish packages or Differentials built against -stable!!!"
        echo "=========================================================================="

  build-local:
    desc: "Build the current package against the unstable and the default local repo"
    cmds:
      - task: build
        vars: 
          PROFILE: 'local-unstable-x86_64'

  # Modify packages
  bump:
    desc: Bump current release
    dir: '{{ .TASKFILE_DIR }}'
    cmds:
      - |
        if [[ -e package.yml ]]; then
        	python /usr/share/ypkg/ybump.py package.yml;
        else
        	./Scripts/pbump.py pspec.xml;
        fi;
  
  convert:
    desc: Convert pspec to package.yml
    dir: '{{ .TASKFILE_DIR }}'
    preconditions:
      - test -f pspec.xml
    cmds:
      - ./Scripts/yconvert.py pspec.xml

  # Other utilities
  clean:
    desc: Clean current tree
    preconditions:
      - test -f *.eopkg
    cmds:
      - rm *.eopkg -fv

  pull:
    desc: Pull/rebase latest changes
    cmds:
      - git pull --rebase

  switch-domains:
    desc: Update local repositories to use correct hostname
    dir: '{{ .TASKFILE_DIR }}'
    cmds:
      - go run ./Go/switch_repo_domains.go
